
; This file defines how Heat is gained / lost in pursuits.
;
; For the TECHNICAL DETAILS AND LIMITATIONS of the features in here, see the "APPENDIX.txt" file.
; The UNEDITED VALUES in this file resemble the game's vanilla (i.e. unmodified) values.






; ── ■ │ PASSIVE HEAT │ ■ ─────────────────────────────────────────────────────────────────────────

[Heat:Time]
; Whether your Heat increases passively over time in active pursuits.
;
; ■ FORMAT: heatXY = increasesPassively (FREE-ROAM; "default" if omitted)
;           raceXY = increasesPassively (RACES;     "default" if omitted)
;
; • The "0x80deb840" VltEd arrays define the passive Heat gain at each Blacklist rank.
; • Each value must be either "true" or "false".
; • You can define a "default" value.

default = true

heat01 = true
heat02 = true
heat03 = true
heat04 = true
heat05 = true
heat06 = true
heat07 = true
heat08 = true
heat09 = true
heat10 = true

race01 = true
race02 = true
race03 = true
race04 = true
race05 = true
race06 = true
race07 = true
race08 = true
race09 = true
race10 = true




[Time:Challenges]
; How long (in seconds) it takes to gain a Heat level passively in Challenge Series pursuits.
;
; ■ FORMAT: heatXY = escalationScale (FREE-ROAM; "default" if omitted)
;           raceXY = escalationScale (RACES;     "default" if omitted)
;
; • These escalation scales are also affected by the "[Heat:Time]" settings above.
; • The "TimePerHeatLevel" VltEd parameter acts as a multiplier for all escalation scales.
; • The vanilla game always recycles Sonny's escalation scales for Challenge Series events.
; • Your Heat can only increase in Challenge Series events with appropriate VltEd settings.
; • Each value must be a non-negative decimal or whole number.
; • You can define a "default" value.

default = 600.0

heat01 = 600.0
heat02 = 600.0
heat03 = 600.0
heat04 = 600.0
heat05 = 600.0
heat06 = 600.0
heat07 = 600.0
heat08 = 600.0
heat09 = 600.0
heat10 = 600.0

race01 = 600.0
race02 = 600.0
race03 = 600.0
race04 = 600.0
race05 = 600.0
race06 = 600.0
race07 = 600.0
race08 = 600.0
race09 = 600.0
race10 = 600.0






; ── ■ │ COP DEPLOYMENT │ ■ ───────────────────────────────────────────────────────────────────────

[Heat:Deployments]
; How much Heat (in levels) you gain / lose from cop deployments in pursuits.
;
; ■ FORMAT: heatXY = {chaser, support, Helicopter}HeatChange (FREE-ROAM; "default" if omitted)
;           raceXY = {chaser, support, Helicopter}HeatChange (RACES;     "default" if omitted)
;
; • Whenever you're in "COOLDOWN" mode, cop deployments don't affect your Heat.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make cop deployments decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value tuple.

default = 0.0, 0.0, 0.0

heat01 = 0.0, 0.0, 0.0
heat02 = 0.0, 0.0, 0.0
heat03 = 0.0, 0.0, 0.0
heat04 = 0.0, 0.0, 0.0
heat05 = 0.0, 0.0, 0.0
heat06 = 0.0, 0.0, 0.0
heat07 = 0.0, 0.0, 0.0
heat08 = 0.0, 0.0, 0.0
heat09 = 0.0, 0.0, 0.0
heat10 = 0.0, 0.0, 0.0

race01 = 0.0, 0.0, 0.0
race02 = 0.0, 0.0, 0.0
race03 = 0.0, 0.0, 0.0
race04 = 0.0, 0.0, 0.0
race05 = 0.0, 0.0, 0.0
race06 = 0.0, 0.0, 0.0
race07 = 0.0, 0.0, 0.0
race08 = 0.0, 0.0, 0.0
race09 = 0.0, 0.0, 0.0
race10 = 0.0, 0.0, 0.0




[Heat:Roadblocks]
; How much Heat (in levels) you gain / lose from roadblock deployments.
;
; ■ FORMAT: heatXY = {roadblock, spikes}HeatChange (FREE-ROAM; "default" if omitted)
;           raceXY = {roadblock, spikes}HeatChange (RACES;     "default" if omitted)
;
; • Whenever you're in "COOLDOWN" mode, roadblock deployments don't affect your Heat.
; • "roadblockHeatChange" triggers for every roadblock without exception.
; • "spikesHeatChange"    triggers for each spike strip separately.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make roadblock deployments decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value pair.

default = 0.0, 0.0

heat01 = 0.0, 0.0
heat02 = 0.0, 0.0
heat03 = 0.0, 0.0
heat04 = 0.0, 0.0
heat05 = 0.0, 0.0
heat06 = 0.0, 0.0
heat07 = 0.0, 0.0
heat08 = 0.0, 0.0
heat09 = 0.0, 0.0
heat10 = 0.0, 0.0

race01 = 0.0, 0.0
race02 = 0.0, 0.0
race03 = 0.0, 0.0
race04 = 0.0, 0.0
race05 = 0.0, 0.0
race06 = 0.0, 0.0
race07 = 0.0, 0.0
race08 = 0.0, 0.0
race09 = 0.0, 0.0
race10 = 0.0, 0.0






; ── ■ │ COP TAGGING │ ■ ──────────────────────────────────────────────────────────────────────────

[Heat:Tagging]
; How much Heat (in levels) you gain / lose from tagging any cop vehicle.
;
; ■ FORMAT: heatXY = heatChange (FREE-ROAM; "default" if omitted)
;           raceXY = heatChange (RACES;     "default" if omitted)
;
; • These Heat changes are on top of the [Tagging:Vehicles]" settings below.
; • Whenever you're in "COOLDOWN" mode, tagging cop vehicles doesn't affect your Heat.
; • You can only tag each cop vehicle once, much like the "cops damaged" statistic in-game.
; • A cop vehicle counts as tagged regardless of whether you actually caused the collision.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make tagging any cop vehicle decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

default = 0.0

heat01 = 0.0
heat02 = 0.0
heat03 = 0.0
heat04 = 0.0
heat05 = 0.0
heat06 = 0.0
heat07 = 0.0
heat08 = 0.0
heat09 = 0.0
heat10 = 0.0

race01 = 0.0
race02 = 0.0
race03 = 0.0
race04 = 0.0
race05 = 0.0
race06 = 0.0
race07 = 0.0
race08 = 0.0
race09 = 0.0
race10 = 0.0




[Tagging:Vehicles]
; How much Heat (in levels) you gain / lose from tagging specific cop vehicles.
;
; ■ FORMAT: pvehicle = heatChange ("default" if omitted)
;
; • These Heat changes are on top of the [Heat:Tagging]" settings above.
; • Whenever you're in "COOLDOWN" mode, tagging cop vehicles doesn't affect your Heat.
; • You can only tag each cop vehicle once, much like the "cops damaged" statistic in-game.
; • A cop vehicle counts as tagged regardless of whether you actually caused the collision.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make tagging specific cop vehicles decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

; Cop vehicles without explicit Heat changes (uncomment to enable)
; default = 0.0

; Regular patrol cars (uncomment to enable)
; copmidsize  = 0.0
; copghost    = 0.0
; copgto      = 0.0
; copgtoghost = 0.0

; Elite street-racing unit (uncomment to enable)
; copsporthench = 0.0
; copsportghost = 0.0
; copsport      = 0.0

; Heavy support units (uncomment to enable)
; copsuv       = 0.0
; copsuvl      = 0.0
; copsuvpatrol = 0.0

; Sergeant Cross (uncomment to enable)
; copcross = 0.0

; Helicopter (uncomment to enable)
; copheli = 0.0






; ── ■ │ COP ASSAULT │ ■ ──────────────────────────────────────────────────────────────────────────

[Heat:Assault]
; How much Heat (in levels) you gain / lose from assaulting any cop vehicle.
;
; ■ FORMAT: heatXY = heatChange (FREE-ROAM; "default" if omitted)
;           raceXY = heatChange (RACES;     "default" if omitted)
;
; • These Heat changes are on top of the "[Assault:Vehicles]" settings below.
; • Whenever you're in "COOLDOWN" mode, assaulting cop vehicles doesn't affect your Heat.
; • The conditions for assault are the same as those for the "ramming a cop" infraction.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make assaulting any cop vehicle decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

default = 0.0

heat01 = 0.0
heat02 = 0.0
heat03 = 0.0
heat04 = 0.0
heat05 = 0.0
heat06 = 0.0
heat07 = 0.0
heat08 = 0.0
heat09 = 0.0
heat10 = 0.0

race01 = 0.0
race02 = 0.0
race03 = 0.0
race04 = 0.0
race05 = 0.0
race06 = 0.0
race07 = 0.0
race08 = 0.0
race09 = 0.0
race10 = 0.0




[Assault:Vehicles]
; How much Heat (in levels) you gain / lose from assaulting specific cop vehicles.
;
; ■ FORMAT: pvehicle = heatChange ("default" if omitted)
;
; • These Heat changes are on top of the [Heat:Assault]" settings above.
; • Whenever you're in "COOLDOWN" mode, tagging cop vehicles doesn't affect your Heat.
; • You can only tag each cop vehicle once, much like the "cops damaged" statistic in-game.
; • A cop vehicle counts as tagged regardless of whether you actually caused the collision.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make tagging specific cop vehicles decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

; Cop vehicles without explicit Heat changes (uncomment to enable)
; default = 0.0

; Regular patrol cars (uncomment to enable)
; copmidsize  = 0.0
; copghost    = 0.0
; copgto      = 0.0
; copgtoghost = 0.0

; Elite street-racing unit (uncomment to enable)
; copsporthench = 0.0
; copsportghost = 0.0
; copsport      = 0.0

; Heavy support units (uncomment to enable)
; copsuv       = 0.0
; copsuvl      = 0.0
; copsuvpatrol = 0.0

; Sergeant Cross (uncomment to enable)
; copcross = 0.0

; Helicopter (uncomment to enable)
; copheli = 0.0




[Assault:Limit]
; How many times you can receive credit for assaulting a single cop vehicle.
;
; ■ FORMAT: heatXY = maxNumAssaultsPerCop (FREE-ROAM)
;           raceXY = maxNumAssaultsPerCop (RACES)
;
; • This limit affects the "[Heat:Assault]" and "[Assault:Vehicles]" settings above.
; • Assaults are only limited at Heat levels for which you define a valid limit value.
; • Bartender tracks the assault count separately for each cop vehicle that spawns.
; • Each value must be a whole number between 0 and 254 (inclusive).
; • You can't define a "default" value.

heat01 = 1
heat02 = 1
heat03 = 1
heat04 = 1
heat05 = 1
heat06 = 1
heat07 = 1
heat08 = 1
heat09 = 1
heat10 = 1

race01 = 1
race02 = 1
race03 = 1
race04 = 1
race05 = 1
race06 = 1
race07 = 1
race08 = 1
race09 = 1
race10 = 1






; ── ■ │ COP WRECKING │ ■ ─────────────────────────────────────────────────────────────────────────

[Heat:Wrecking]
; How much Heat (in levels) you gain / lose from destroying any cop vehicle.
;
; ■ FORMAT: heatXY = heatChange (FREE-ROAM; "default" if omitted)
;           raceXY = heatChange (RACES;     "default" if omitted)
;
; • These Heat changes are on top of the "[Wrecking:Vehicles]" settings below. 
; • Whenever you're in "COOLDOWN" mode, destroying cop vehicles doesn't affect your Heat.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make destroying any cop vehicle decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

default = 0.0

heat01 = 0.0
heat02 = 0.0
heat03 = 0.0
heat04 = 0.0
heat05 = 0.0
heat06 = 0.0
heat07 = 0.0
heat08 = 0.0
heat09 = 0.0
heat10 = 0.0

race01 = 0.0
race02 = 0.0
race03 = 0.0
race04 = 0.0
race05 = 0.0
race06 = 0.0
race07 = 0.0
race08 = 0.0
race09 = 0.0
race10 = 0.0




[Wrecking:Vehicles]
; How much Heat (in levels) you gain / lose from destroying specific cop vehicles.
;
; ■ FORMAT: pvehicle = heatChange ("default" if omitted)
;
; • These Heat changes are on top of the "[Heat:Wrecking]" settings above. 
; • Whenever you're in "COOLDOWN" mode, destroying cop vehicles doesn't affect your Heat.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make destroying specific cop vehicles decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

; Cop vehicles without explicit Heat changes (uncomment to enable)
; default = 0.0

; Regular patrol cars (uncomment to enable)
; copmidsize  = 0.0
; copghost    = 0.0
; copgto      = 0.0
; copgtoghost = 0.0

; Elite street-racing unit (uncomment to enable)
; copsporthench = 0.0
; copsportghost = 0.0
; copsport      = 0.0

; Heavy support units (uncomment to enable)
; copsuv       = 0.0
; copsuvl      = 0.0
; copsuvpatrol = 0.0

; Sergeant Cross (uncomment to enable)
; copcross = 0.0

; Helicopter (uncomment to enable)
; copheli = 0.0






; ── ■ │ MISCELLANEOUS │ ■ ────────────────────────────────────────────────────────────────────────

[Heat:Traffic]
; How much Heat (in levels) you gain / lose from hitting any traffic vehicle.
;
; ■ FORMAT: heatXY = heatChange (FREE-ROAM; "default" if omitted)
;           raceXY = heatChange (RACES;     "default" if omitted)
;
; • Whenever you're in "COOLDOWN" mode, hitting traffic vehicles doesn't affect your Heat.
; • You only get credit for hitting traffic cars if the game judges you to be at fault.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make hitting any traffic vehicle decrease your Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

default = 0.0

heat01 = 0.0
heat02 = 0.0
heat03 = 0.0
heat04 = 0.0
heat05 = 0.0
heat06 = 0.0
heat07 = 0.0
heat08 = 0.0
heat09 = 0.0
heat10 = 0.0

race01 = 0.0
race02 = 0.0
race03 = 0.0
race04 = 0.0
race05 = 0.0
race06 = 0.0
race07 = 0.0
race08 = 0.0
race09 = 0.0
race10 = 0.0




[Heat:Property]
; How much generic property damage (in cash) amounts to a Heat change of one level.
;
; ■ FORMAT: heatXY = damagePerLevel (FREE-ROAM; "default" if omitted)
;           raceXY = damagePerLevel (RACES;     "default" if omitted)
;
; • Whenever you're in "COOLDOWN" mode, property damage doesn't affect your Heat.
; • Generic property damage is just one part of many that affect cost to state.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make generic property damage decrease your Heat instead.
; • Values of 0 disable Heat changes through generic propery damage entirely.
; • Each value must be a whole number.
; • You can define a "default" value.

default = 0

heat01 = 0
heat02 = 0
heat03 = 0
heat04 = 0
heat05 = 0
heat06 = 0
heat07 = 0
heat08 = 0
heat09 = 0
heat10 = 0

race01 = 0
race02 = 0
race03 = 0
race04 = 0
race05 = 0
race06 = 0
race07 = 0
race08 = 0
race09 = 0
race10 = 0