
; This file defines parameters for Speedbreaker-related settings.
;
; For the TECHNICAL DETAILS AND LIMITATIONS of the features in here, see the "APPENDIX.txt" file.
; The UNEDITED VALUES in this file match the game's vanilla (i.e. unmodified) values.






; ── ■ │ VANILLA MECHANICS │ ■ ────────────────────────────────────────────────────────────────────

[Speedbreaker:Mechanics]
; Whether the Speedbreaker's vanilla recharging mechanics work in pursuits.
;
; ■ FORMAT: heatXY = {speed, drift}RechargeEnabled (FREE-ROAM; -> "default" if omitted)
;           raceXY = {speed, drift}RechargeEnabled (RACES;     -> "heatXY"  if omitted)
;
; • In the vanilla game, you can recharge the Speedbreaker by driving fast or drifting.
; • Each value must be either "true" or "false".
; • You can define a "default" value pair.

default = true, true

heat01 = true, true
heat02 = true, true
heat03 = true, true
heat04 = true, true
heat05 = true, true
heat06 = true, true
heat07 = true, true
heat08 = true, true
heat09 = true, true
heat10 = true, true

race01 = true, true
race02 = true, true
race03 = true, true
race04 = true, true
race05 = true, true
race06 = true, true
race07 = true, true
race08 = true, true
race09 = true, true
race10 = true, true






; ── ■ │ COP WRECKING │ ■ ─────────────────────────────────────────────────────────────────────────

[Speedbreaker:Wrecking]
; How much speedbreaker charge (in seconds) you gain / lose from wrecking any cop vehicle.
;
; ■ FORMAT: heatXY = chargeChange (FREE-ROAM; -> "default" if omitted)
;           raceXY = chargeChange (RACES;     -> "heatXY"  if omitted)
;
; • These charge changes are on top of the "[Wrecking:Vehicles]" settings below.
; • To restrict charge changes, see the "[Wrecking:Gains]" and "[Wrecking:Losses]" settings below.
; • For races, this feature requires the vanilla game to track the number of cops wrecked in races.
; • See the "[Pursuits:Races]" settings in the "General.ini" file to enable tracking in races.
; • Bartender always respects the Speedbreaker's hard-coded charge limits.
; • Negative values make wrecking decrease charge instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

default = 0.0

heat01 = 0.0
heat02 = 0.0
heat03 = 0.0
heat04 = 0.0
heat05 = 0.0
heat06 = 0.0
heat07 = 0.0
heat08 = 0.0
heat09 = 0.0
heat10 = 0.0

race01 = 0.0
race02 = 0.0
race03 = 0.0
race04 = 0.0
race05 = 0.0
race06 = 0.0
race07 = 0.0
race08 = 0.0
race09 = 0.0
race10 = 0.0




[Wrecking:Vehicles]
; How much speedbreaker charge (in seconds) you gain / lose from wrecking a given cop vehicle.
;
; ■ FORMAT: pvehicle = chargeChange (-> "default" if omitted)
;
; • These charge changes are on top of the "[Speedbreaker:Wrecking]" settings above.
; • To restrict charge changes, see the "[Wrecking:Gains]" and "[Wrecking:Losses]" settings below.
; • For races, this feature requires the vanilla game to track the number of cops wrecked in races.
; • See the "[Pursuits:Races]" settings in the "General.ini" file to enable tracking in races.
; • Bartender always respects the Speedbreaker's hard-coded charge limits.
; • Negative values make destroying cops of those types decrease charge instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

; Vehicles without explicit charge changes (uncomment to enable)
; default = 0.0

; Regular patrol cars (uncomment to enable)
; copmidsize  = 0.0
; copghost    = 0.0
; copgto      = 0.0
; copgtoghost = 0.0

; Elite street-racing unit (uncomment to enable)
; copsporthench = 0.0
; copsportghost = 0.0
; copsport      = 0.0

; Heavy support units (uncomment to enable)
; copsuv       = 0.0
; copsuvl      = 0.0
; copsuvpatrol = 0.0

; Sergeant Cross (uncomment to enable)
; copcross = 0.0

; Helicopter (uncomment to enable)
; copheli = 0.0




[Wrecking:Gains]
; Whether you can gain Speedbreaker charge through wrecking while the Speedbreaker is (in)active.
;
; ■ FORMAT: heatXY = canGainWhile{Active, Inactive} (FREE-ROAM; -> "default" if omitted)
;           raceXY = canGainWhile{Active, Inactive} (RACES;     -> "heatXY"  if omitted)
;
; • This applies to both the "[Speedbreaker:Wrecking]" and "[Wrecking:Vehicles]" settings above.
; • Each value must be either "true" or "false".
; • You can define a "default" value pair.

default = true, true

heat01 = true, true
heat02 = true, true
heat03 = true, true
heat04 = true, true
heat05 = true, true
heat06 = true, true
heat07 = true, true
heat08 = true, true
heat09 = true, true
heat10 = true, true

race01 = true, true
race02 = true, true
race03 = true, true
race04 = true, true
race05 = true, true
race06 = true, true
race07 = true, true
race08 = true, true
race09 = true, true




[Wrecking:Losses]
; Whether you can lose Speedbreaker charge through wrecking while the Speedbreaker is (in)active.
;
; ■ FORMAT: heatXY = canLoseWhile{Active, Inactive} (FREE-ROAM; -> "default" if omitted)
;           raceXY = canLoseWhile{Active, Inactive} (RACES;     -> "heatXY"  if omitted)
;
; • This applies to both the "[Speedbreaker:Wrecking]" and "[Wrecking:Vehicles]" settings above.
; • Each value must be either "true" or "false".
; • You can define a "default" value pair.

default = true, true

heat01 = true, true
heat02 = true, true
heat03 = true, true
heat04 = true, true
heat05 = true, true
heat06 = true, true
heat07 = true, true
heat08 = true, true
heat09 = true, true
heat10 = true, true

race01 = true, true
race02 = true, true
race03 = true, true
race04 = true, true
race05 = true, true
race06 = true, true
race07 = true, true
race08 = true, true
race09 = true, true