
; This file defines how Heat is gained / lost in pursuits.
;
; For the TECHNICAL DETAILS AND LIMITATIONS of the features in here, see the "APPENDIX.txt" file.
; The UNEDITED VALUES in this file resemble the game's vanilla (i.e. unmodified) values.






; ── ■ │ PASSIVE HEAT │ ■ ─────────────────────────────────────────────────────────────────────────

[Heat:Time]
; Whether Heat increases passively over time in pursuits.
;
; ■ FORMAT: heatXY = increasesPassively (FREE-ROAM; -> "default" if omitted)
;           raceXY = increasesPassively (RACES;     -> "heatXY"  if omitted)
;
; • The "0x80deb840" VltEd arrays define the passive Heat gain at each Blacklist rank.
; • Each value must be either "true" or "false".
; • You can define a "default" value.

default = true

heat01 = true
heat02 = true
heat03 = true
heat04 = true
heat05 = true
heat06 = true
heat07 = true
heat08 = true
heat09 = true
heat10 = true

race01 = true
race02 = true
race03 = true
race04 = true
race05 = true
race06 = true
race07 = true
race08 = true
race09 = true
race10 = true




[Heat:Deployment]
; How much Heat (in levels) racers gain / lose from cop deployments in pursuits.
;
; ■ FORMAT: heatXY = {chaser, support, Helicopter}HeatChange (FREE-ROAM; -> "default" if omitted)
;           raceXY = {chaser, support, Helicopter}HeatChange (RACES;     -> "heatXY"  if omitted)
;
; • Whenever a racer is in "COOLDOWN" mode, cop deployments don't affect Heat.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make cop deployments decrease Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value tuple.

default = 0.0, 0.0, 0.0

heat01 = 0.0, 0.0, 0.0
heat02 = 0.0, 0.0, 0.0
heat03 = 0.0, 0.0, 0.0
heat04 = 0.0, 0.0, 0.0
heat05 = 0.0, 0.0, 0.0
heat06 = 0.0, 0.0, 0.0
heat07 = 0.0, 0.0, 0.0
heat08 = 0.0, 0.0, 0.0
heat09 = 0.0, 0.0, 0.0
heat10 = 0.0, 0.0, 0.0

race01 = 0.0, 0.0, 0.0
race02 = 0.0, 0.0, 0.0
race03 = 0.0, 0.0, 0.0
race04 = 0.0, 0.0, 0.0
race05 = 0.0, 0.0, 0.0
race06 = 0.0, 0.0, 0.0
race07 = 0.0, 0.0, 0.0
race08 = 0.0, 0.0, 0.0
race09 = 0.0, 0.0, 0.0
race10 = 0.0, 0.0, 0.0




[Heat:Roadblocks]
; How much Heat (in levels) racers gain / lose from roadblock deployments.
;
; ■ FORMAT: heatXY = {roadblock, spikes}HeatChange (FREE-ROAM; -> "default" if omitted)
;           raceXY = {roadblock, spikes}HeatChange (RACES;     -> "heatXY"  if omitted)
;
; • Whenever a racer is in "COOLDOWN" mode, roadblock deployments don't affect Heat.
; • "roadblockHeatChange" triggers for every roadblock without exception.
; • "spikesHeatChange"    triggers for each spike strip separately.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make roadblock deployments decrease Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value pair.

default = 0.0, 0.0

heat01 = 0.0, 0.0
heat02 = 0.0, 0.0
heat03 = 0.0, 0.0
heat04 = 0.0, 0.0
heat05 = 0.0, 0.0
heat06 = 0.0, 0.0
heat07 = 0.0, 0.0
heat08 = 0.0, 0.0
heat09 = 0.0, 0.0
heat10 = 0.0, 0.0

race01 = 0.0, 0.0
race02 = 0.0, 0.0
race03 = 0.0, 0.0
race04 = 0.0, 0.0
race05 = 0.0, 0.0
race06 = 0.0, 0.0
race07 = 0.0, 0.0
race08 = 0.0, 0.0
race09 = 0.0, 0.0
race10 = 0.0, 0.0






; ── ■ │ COP WRECKING │ ■ ─────────────────────────────────────────────────────────────────────────

[Heat:Wrecking]
; How much Heat (in levels) racers gain / lose from wrecking any cop vehicle.
;
; ■ FORMAT: heatXY = heatChange (FREE-ROAM; -> "default" if omitted)
;           raceXY = heatChange (RACES;     -> "heatXY"  if omitted)
;
; • These Heat changes are on top of the "[Wrecking:Vehicles]" settings below. 
; • Whenever a racer is in "COOLDOWN" mode, wrecking cop vehicles doesn't affect Heat.
; • For races, this feature requires the vanilla game to track the number of cops wrecked in races.
; • See the "General.ini" file of the "Basic" feature set to enable tracking in races.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make wrecking decrease Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

default = 0.0

heat01 = 0.0
heat02 = 0.0
heat03 = 0.0
heat04 = 0.0
heat05 = 0.0
heat06 = 0.0
heat07 = 0.0
heat08 = 0.0
heat09 = 0.0
heat10 = 0.0

race01 = 0.0
race02 = 0.0
race03 = 0.0
race04 = 0.0
race05 = 0.0
race06 = 0.0
race07 = 0.0
race08 = 0.0
race09 = 0.0
race10 = 0.0




[Wrecking:Vehicles]
; How much Heat (in levels) racers gain / lose from wrecking a given cop vehicle.
;
; ■ FORMAT: pvehicle = heatChange (-> "default" if omitted)
;
; • These Heat changes are on top of the "[Heat:Wrecking]" settings above. 
; • Whenever a racer is in "COOLDOWN" mode, wrecking cop vehicles doesn't affect Heat.
; • If you define no valid Heat changes and no "default" value, Bartender disables this feature.
; • A Heat change can only be valid if its vehicle is also valid.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make wrecking cops of those types decrease Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value.

; Vehicles without explicit Heat changes (uncomment to enable)
; default = 0.0

; Regular patrol cars (uncomment to enable)
; copmidsize  = 0.0
; copghost    = 0.0
; copgto      = 0.0
; copgtoghost = 0.0

; Elite street-racing unit (uncomment to enable)
; copsporthench = 0.0
; copsportghost = 0.0
; copsport      = 0.0

; Heavy support units (uncomment to enable)
; copsuv       = 0.0
; copsuvl      = 0.0
; copsuvpatrol = 0.0

; Sergeant Cross (uncomment to enable)
; copcross = 0.0

; Helicopter (uncomment to enable)
; copheli = 0.0






; ── ■ │ VEHICLE COLLISIONS │ ■ ───────────────────────────────────────────────────────────────────

[Heat:Collisions]
; How much Heat (in levels) racers gain / lose from colliding with other vehicles.
;
; ■ FORMAT: heatXY = {cop, traffic}HeatChange (FREE-ROAM; -> "default" if omitted)
;           raceXY = {cop, traffic}HeatChange (RACES;     -> "heatXY"  if omitted)
;
; • These Heat changes are on top of the "[Collisions:Assault]" settings below.
; • Whenever a racer is in "COOLDOWN" mode, vehicle collisions don't affect Heat.
; • The game counts these collisions only once per cop / traffic car.
; • The game counts these collisions regardless of who's at fault.
; • For races, this feature requires the vanilla game to track collisions in races.
; • See the "General.ini" file of the "Basic" feature set to enable tracking in races.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make collisions decrease Heat instead.
; • Each value must be a decimal or whole number.
; • You can define a "default" value pair.

default = 0.0, 0.0

heat01 = 0.0, 0.0
heat02 = 0.0, 0.0
heat03 = 0.0, 0.0
heat04 = 0.0, 0.0
heat05 = 0.0, 0.0
heat06 = 0.0, 0.0
heat07 = 0.0, 0.0
heat08 = 0.0, 0.0
heat09 = 0.0, 0.0
heat10 = 0.0, 0.0

race01 = 0.0, 0.0
race02 = 0.0, 0.0
race03 = 0.0, 0.0
race04 = 0.0, 0.0
race05 = 0.0, 0.0
race06 = 0.0, 0.0
race07 = 0.0, 0.0
race08 = 0.0, 0.0
race09 = 0.0, 0.0
race10 = 0.0, 0.0




[Collisions:Assault]
; How much Heat (in levels) racers gain / lose from assaulting a cop vehicle.
;
; ■ FORMAT: heatXY = heatChange, onlyOncePerCop (FREE-ROAM; -> "default" if omitted)
;           raceXY = heatChange, onlyOncePerCop (RACES;     -> "heatXY"  if omitted)
;
; • These Heat changes are on top of the "[Heat:Collisions]" settings above.
; • Whenever a racer is in "COOLDOWN" mode, assaulting cop vehicles doesn't affect Heat.
; • The conditions for assault are the same as those for the "ramming a cop" infraction.
; • The game can be rather inconsistent at judging whether a collision counts as assault.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make assaulting cop vehicles decrease Heat instead.
; • Each Heat-change value must be a decimal or whole number.
; • Each repetition flag must be either "true" or "false"
; • You can define a "default" value pair.

default = 0.0, true

heat01 = 0.0, true
heat02 = 0.0, true
heat03 = 0.0, true
heat04 = 0.0, true
heat05 = 0.0, true
heat06 = 0.0, true
heat07 = 0.0, true
heat08 = 0.0, true
heat09 = 0.0, true
heat10 = 0.0, true

race01 = 0.0, true
race02 = 0.0, true
race03 = 0.0, true
race04 = 0.0, true
race05 = 0.0, true
race06 = 0.0, true
race07 = 0.0, true
race08 = 0.0, true
race09 = 0.0, true
race10 = 0.0, true






; ── ■ │ PROPERTY DAMAGE │ ■ ──────────────────────────────────────────────────────────────────────

[Heat:Damage]
; How much generic property damage (in cash) amounts to a Heat change of one level.
;
; ■ FORMAT: heatXY = damagePerLevel (FREE-ROAM; -> "default" if omitted)
;           raceXY = damagePerLevel (RACES;     -> "heatXY"  if omitted)
;
; • Whenever a racer is in "COOLDOWN" mode, property damage doesn't affect Heat.
; • Generic property damage is just one part of many that affect cost to state.
; • For races, this feature requires the vanilla game to track property damage in races.
; • See "General.ini" file of the "Basic" feature set to enable tracking in races.
; • Bartender always respects the current Heat-level limits as defined in VltEd.
; • Negative values make property damage decrease Heat instead.
; • Values of 0 disable Heat changes through propery damage.
; • Each value must be a whole number.
; • You can define a "default" value.

default = 0

heat01 = 0
heat02 = 0
heat03 = 0
heat04 = 0
heat05 = 0
heat06 = 0
heat07 = 0
heat08 = 0
heat09 = 0
heat10 = 0

race01 = 0
race02 = 0
race03 = 0
race04 = 0
race05 = 0
race06 = 0
race07 = 0
race08 = 0
race09 = 0
race10 = 0